### ISSUE TITLE
Register .vala files as autoloads

### ISSUE THREAD

**Issue by mcandre** [emacsorphanage/vala-mode#1]
Please add autoloads so that vala-mode automatically triggers when `.vala` files are opened in Emacs.

See vimrc-mode for reference.

https://github.com/mcandre/vimrc-mode/blob/master/vimrc-mode.el#L1225-L1227

**Comment by yashi** [comment]
Just noticed this issue and created a pull request.  Let me know if anything needs to be done.
Thanks.
