### ISSUE TITLE
Please use style for indentation, not hard-wired settings

### ISSUE THREAD

**Issue by rrthomas** [emacsorphanage/vala-mode#8]
I just wondered why indentation of comments was not behaving as I expected, and discovered this is because `vala-mode` sets up the style "manually" at the end of `vala-mode`. Would you consider using a style that can be changed, instead? If so, I'd be happy to work on a patch for `vala-mode.el` to achieve this.

**Comment by rrthomas** [comment]
After a little more investigation, it seemed the simple thing to do was add a C style to `c-default-style` for vala-mode, but only if one does not already exist, so the user can still customize `c-default-style` to override the setting.

**Comment by purcell** [comment]
I imagine there's even a macro for defining C-based major modes, so perhaps there's some general machinery that can tidy things up further, or make customisations like this natural.

**Comment by rrthomas** [comment]
As I continue to use Vala, I could well end up looking into this!
